[package]
name = "luars"
version = "0.1.0"
edition = "2024"

[features]
default = []
async = ["dep:tokio"]
wasm = []
loadlib = ["dep:libloading"]

[dependencies]
emmylua_parser.workspace = true
libloading = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
itoa = "1.0"  # Fast integer formatting (10x faster than format!)
ryu = "1.0"   # Fast float formatting
tempfile = "3.10"  # For io.tmpfile()
