[package]
name = "luars"
version = "0.1.0"
edition = "2024"

[features]
default = []
async = ["dep:tokio"]
wasm = []
loadlib = ["dep:libloading"]

[dependencies]
libloading = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
hashbrown = { version = "0.16.1", features = ["raw-entry"] }

