[package]
name = "luars"
version = "0.1.0"
edition = "2024"
authors = ["CppCXY"]
description = "A library for lua 5.5 runtime implementation in Rust"
license = "MIT"
repository = "https://github.com/CppCXY/lua-rs"
readme = "README.md"
keywords = ["lua", "runtime", "interpreter"]
categories = ["development-tools"]

[features]
default = []
serde = ["dep:serde", "dep:serde_json"]

[dependencies]
ahash = "0.8"
rand = "0.8"
chrono = "0.4"
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = { version = "1.0", optional = true }
