[workspace]
resolver = "2"
members = [
    "crates/*"
]

[workspace.dependencies]
# local
luars = { path = "crates/luars", version = "0.1.0" }

# external
emmylua_parser = "0.19.0"
libloading = "0.9"
tokio = { version = "1.42", features = ["rt-multi-thread", "time", "sync", "macros"] }
wasm-bindgen = "0.2"
