[workspace]
resolver = "2"
members = [
    "crates/*", 
    "examples/luars-example"
]

[workspace.dependencies]
# local
luars = { path = "crates/luars", version = "0.4.0" }
luars-derive = { path = "crates/luars-derive", version = "0.2.0" }

wasm-bindgen = "0.2"
ahash = "0.8"
rand = "0.8"
chrono = "0.4"
itoa = "1"
